name: Atlas Connect Build

on:
  workflow_dispatch:
  push:
    branches:
      - atlas-build

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  build-branded-windows:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: "atlas-connect"
